name: Demo
options:
  bundleIdPrefix: dev.mt
packages:
  HotReloading:
    url: https://github.com/johnno1962/HotReloading.git
    branch: main
  Inject:
    url: https://github.com/krzysztofzablocki/Inject.git
    branch: main
targets:
  Demo_iOS:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Demo
        excludes:
          - Info_watchOS.plist
    dependencies:
      - sdk: SwiftUI.framework
      - package: HotReloading
      - package: Inject
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "Demo/Info.plist"
        MARKETING_VERSION: 1
        OTHER_LDFLAGS: "-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup"
  Demo_macOS:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Demo
        excludes:
          - Info_watchOS.plist
    dependencies:
      - sdk: SwiftUI.framework
      - package: HotReloading
      - package: Inject
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "Demo/Info.plist"
        MARKETING_VERSION: 1
        OTHER_LDFLAGS: "-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup"
  Demo_watchOS:
    type: application
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: Demo
        excludes:
          - Info.plist
    dependencies:
      - sdk: SwiftUI.framework
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "Demo/Info_watchOS.plist"
        MARKETING_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: dev.mt.Demo-iOS.watchkitapp
