name: Demo
options:
  bundleIdPrefix: dev.mt
packages:
  HotReloading:
    url: https://github.com/johnno1962/HotReloading.git
    branch: main
  Inject:
    url: https://github.com/krzysztofzablocki/Inject.git
    branch: main
targets:
  Demo_iOS:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/App
        excludes:
          - Info_watchOS.plist
    dependencies:
      - sdk: SwiftUI.framework
      - package: HotReloading
      - package: Inject
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "Sources/App/Info.plist"
        MARKETING_VERSION: 1
        OTHER_LDFLAGS: "-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup"
  Demo_macOS:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources/App
        excludes:
          - Info_watchOS.plist
    dependencies:
      - sdk: SwiftUI.framework
      - package: HotReloading
      - package: Inject
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "Sources/App/Info.plist"
        MARKETING_VERSION: 1
        OTHER_LDFLAGS: "-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup"
  Demo_watchOS:
    type: application
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: Sources/App
        excludes:
          - Info.plist
    dependencies:
      - sdk: SwiftUI.framework
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "Sources/App/Info_watchOS.plist"
        MARKETING_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: dev.mt.Demo-iOS.watchkitapp
  UnitTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Sources/Tests/UnitTests]
    settings:
      GENERATE_INFOPLIST_FILE: true
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Demo_iOS.app/Demo_iOS
schemes:
  App_iOS:
    build:
      targets:
        Demo_iOS: all
    run:
      config: Debug
      excetuable: Demo_iOS
    test:
      config: Debug
      targets:
        - UnitTests
  App_macOS:
    build:
      targets:
        Demo_macOS: all
    run:
      config: Debug
      excetuable: Demo_macOS
  App_watchOS:
    build:
      targets:
        Demo_watchOS: all
    run:
      config: Debug
      excetuable: Demo_watchOS
